print("Hello World!")
print("git init \ngit status \ngit add . \n git commit -m 'message' ")
print("git branch 'BranchName' \ngit checkout 'BranchName' \nthen follow the process of add and commit changes")
print("for seeing an version or old commits use following command \n git log \n git log --all \n git log --all --graph")
print("first set a remote means github repository hosted to another computer \nthis shows github repo comnnected or not \ngit remote -v ")
print("if githun repo not connected or not hosted then \ngit remote add origin 'repo Link' \ngit remote set-url origin 'repo Link'")
print("push the local file or folders on the github using this following commands \ngit push origin main \ngit push -u origin main")
print("pull the github folders or file into local machine \n this is used to merge and download\ngit pull origin main \n this is only used to only download\ngit fetch ")